apiVersion: v1
data:
  AWS_ACCESS_KEY_ID: bWluaW8=
  AWS_SECRET_ACCESS_KEY: bWluaW8xMjM=
kind: Secret
metadata:
  name: minio-kserve
  namespace: kubeflow-user-example-com
  annotations:
    serving.kserve.io/s3-endpoint: "minio-service.kubeflow:9000"
    serving.kserve.io/s3-usehttps: "0"
    serving.kserve.io/s3-useanoncredential: "false"
type: Opaque
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: minio-kserve
  namespace: kubeflow-user-example-com
secrets:
- name: minio-kserve
---
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: yoda-llm
  namespace: kubeflow-user-example-com
  annotations:
    serving.kserve.io/deploymentMode: RawDeployment
    sidecar.istio.io/inject: "false"
    serving.kserve.io/s3-endpoint: "http://minio-service.kubeflow:9000"
spec:
  predictor:
    minReplicas: 1
    maxReplicas: 1
    serviceAccountName: minio-kserve
    model:
      modelFormat:
        name: huggingface
      storageUri: s3://mlpipeline/v2/artifacts/yoda-finetune/20a01d97-476f-4b54-abb0-e26b4b191952/train-model/4c507a27-595f-4757-9ece-931844b4cdf6/output_model
      args:
        - "--model_id=meta-llama/Llama-3.2-3B-Instruct"
        - "--enable-lora"
        - "--lora-modules=lora=/mnt/models"
        # Required for old GPU
        - "--dtype=half"
        # Reduce KV cache footprint and cap GPU memory usage
        - "--max-model-len=4096"
        - "--gpu-memory-utilization=0.75"
      env:
      # Required for .triton to be writable
      - name: HOME
        value: /tmp
      # HF token so the runtime can pull the gated base model
      - name: HF_TOKEN
        valueFrom:
          secretKeyRef:
            name: hf-token
            key: HF_TOKEN
      resources:
        requests:
          cpu: "2"
          memory: "20Gi"
          nvidia.com/gpu: "1"
        limits:
          cpu: "2"
          memory: "20Gi"
          nvidia.com/gpu: "1"
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: yoda-predictor
  namespace: kubeflow-user-example-com
spec:
  path: /
  to:
    name: yoda-llm-predictor
    weight: 100
    kind: Service
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  port:
    targetPort: yoda-llm-predictor
